### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by TimJentzsch** [uilton-oliveira/VConsoleLib.python#1]
License files clarify how others may use your project.
See [this documentation from GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

Popular open source licenses include MIT and Apache-2.0.

When you add the license via the GitHub web interface, it will suggest popular license templates.
To do that, simply click "Add file" > "Create new file" and choose `LICENSE` as file name. A new button "Choose a license template" will appear which helps you to select an appropriate license.

**Comment by uilton-oliveira** [comment]
Done!
